name: build

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  test:    
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Test      
      shell: pwsh
      run: |
        # workaround of issue #1
        # https://github.com/Arnab-Developer/LogicAppHealthCheck/issues/1
        Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted  
        Install-Module -Name Az.LogicApp
        Set-PSRepository -Name 'PSGallery' -InstallationPolicy Untrusted
        try { Get-AzLogicApp }
        catch { }

        Test-ScriptFileInfo -Path Check-LogicAppHealth.ps1 | Format-List

  powershell-gallery-push:    
    name: PowerShell gallery push
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: "PowerShellGallery"
      url: "https://www.powershellgallery.com/packages/Update-InstalledModules"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Publish      
      shell: pwsh
      run: Publish-Script -Path Check-LogicAppHealth.ps1 -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }}